name: Compile All LaTeX Documents

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/xu-cheng/texlive-full:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find and compile LaTeX files
        run: |
          echo "Buscando archivos main.tex..."
          failures=0
          # Itera sobre cada archivo main.tex encontrado
          find . -type f -name "main.tex" -print0 | while IFS= read -r -d '' file; do
              echo "Compilando $file..."
              dir=$(dirname "$file")
              # Compila en el directorio correspondiente
              (cd "$dir" && latexmk -pdf -silent -f main.tex) || { 
                  echo "ERROR: Falló la compilación de $file"; 
                  failures=$((failures+1)); 
              }
          done
          if [ $failures -gt 0 ]; then
              echo "$failures archivo(s) fallaron en la compilación."
              exit 1
          fi

      - name: Commit and push generated PDFs
        run: |
          # Configurar el directorio seguro para Git
          git config --global --add safe.directory "$(pwd)"
          git config --global user.name "vinograd0v"
          git config --global user.email "mmanosalva@unal.edu.co"
          # Agrega todos los PDFs generados
          find . -type f -name "main.pdf" -print0 | xargs -0 git add -f
          if ! git diff-index --quiet HEAD --; then
              git commit -m "Automated PDF update"
              git push
          else
              echo "No hay cambios a commitear"
          fi
